### ISSUE TITLE
Set up custom record types with Cloudflare folks

### ISSUE THREAD

**Issue by ahounsel** [mozilla-extensions/dnssec-interference#1]

**Comment by chris-wood** [comment]
@ahounsel can we close this?

**Comment by ahounsel** [comment]
@chris-wood IIRC, the custom records weren't set up in time for our initial run of the study. I'm not sure if Ekr wants them for our second run, but do you know if they were ultimately set up?

**Comment by chris-wood** [comment]
> @chris-wood IIRC, the custom records weren't set up in time for our initial run of the study because they needed several days to appear in the zones. I'm not sure if Ekr wants them for our second run, but do you know if they were ultimately set up?

Yes. You can query to get them.

**Comment by ahounsel** [comment]
Looks like this was taken care of!
